### PR TITLE
Third-party libraries excluded from Coveralls

### LINKED ISSUE #17: Exclude external libraries in coveralls

### PR DESCRIPTION
**Pull request by helloimcarmine**
Closes #17.

### CODE REVIEW

**Comment by bassosimone** [comment]
Thanks! However, this is not enough. As you can see [in coveralls.io](https://coveralls.io/builds/4406888), we're currently measuring the coverage of a number of system-wide Python libraries whereas I'd like to measure the coverage of only the code written by us below `neubot_runtime`.

**Comment by helloimcarmine** [comment]
I'v tried to solve it merging the two scripts in .travis.yml, locally it seems to work.

**Comment by bassosimone** [comment]
Carmine and I further worked on this some days ago. The final diff looks good to me, so merging it.

**Comment by bassosimone** [comment]
I've fixed a nonfatal warning by which the coveralls command was not found on the system. All the other warnings are harmless, since they are produced as part of the behavior of the tests (i.e. invalid input is passed to functions expected to check whether input is valid, and those functions produce warnings as a result). Now, it's OK to proceed with merging.

Cc: @DavideAllavena.

**Pull request merged**
